name: LocalPlanDynmap
main: org.micoli.minecraft.localPlan.LocalPlanDynmap
version: 0.2
description: parcel management
depend: [Vault,dynmap, WorldGuard,LocalPlan]
commands:
    lp:
      description: main command 